# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd011eb957f8c187ab51b2bd729130cc4344b32997b2a989fee406a1aa80a5084fde0dfdd63f75d84cc966b5789984a3a47e5b5a83cdbc5ff682b71602941c12

test:
  secret_key_base: 8b93705536382280067c1b89ebcd1a5851676380fe6e3d15912c502c0a18f9c3dd841799de2816e0f7f4afad891de9fa0c295495f9c1d98f6e3151a3b89cfeb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 48e2491167aa14c030ee8bfeb857df2bcdb81d8d44995d1e10a808d6308c36a9032db2dd48098188971b86e84f032ca42e5f75b9e20cf6a7c6d3b3e6f3cb35ef
